In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score
from sklearn.metrics import roc_auc_score,roc_curve,auc
import warnings
warnings.filterwarnings("ignore")


def classification (X_train,X_test,y_train,y_test):

    from sklearn.linear_model import LogisticRegression
    logreg = LogisticRegression(solver='saga', dual=False, tol=0.0001,fit_intercept=1, C=100.0, penalty='elasticnet',max_iter=800, l1_ratio=0, random_state=60)
    logreg.fit(X_train,y_train)
    y_pred = logreg.predict(X_test)
    print('logistic_regression_classification_report',classification_report(y_test,y_pred))
    print('logistic_regression_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('logistic_regression_accuracy_score',accuracy_score(y_test,y_pred))
    print('logistic_regression_f1_score',f1_score(y_test,y_pred, average='micro'))


    from sklearn.ensemble import RandomForestClassifier
    rf = RandomForestClassifier(n_estimators=250, max_depth=15, min_samples_split=10, min_samples_leaf=5).fit(X_train,y_train)
    y_pred = rf.predict(X_test)
    print('random_forest_classification_report',classification_report(y_test,y_pred))
    print('random_forest_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('random_forest_accuracy_score',(accuracy_score(y_test,y_pred)))
    print('random_forest_f1_score',f1_score(y_test,y_pred, average='micro'))

    from sklearn.svm import SVC
    svm = SVC(kernel='rbf',C=1,gamma=0.1)
    svm.fit(X_train,y_train)
    y_pred = svm.predict(X_test)
    print('svm_classification_report',classification_report(y_test,y_pred))
    print('svm_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('svm_accuracy_score',accuracy_score(y_test,y_pred))
    print('svm_f1_score',f1_score(y_test,y_pred, average='micro'))


    from sklearn.neighbors import KNeighborsClassifier
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train,y_train)
    y_pred = knn.predict(X_test)
    print('knn_classification_report',classification_report(y_test,y_pred))
    print('knn_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('knn_accuracy_score',accuracy_score(y_test,y_pred))
    print('knn_f1_score',f1_score(y_test,y_pred, average='micro'))

    from sklearn.naive_bayes import GaussianNB
    gnb = GaussianNB()
    gnb.fit(X_train,y_train)
    y_pred = gnb.predict(X_test)
    print('gaussian_naive_bayes_classification_report',classification_report(y_test,y_pred))
    print('gaussian_naive_bayes_confusion_matrix',confusion_matrix(y_test,y_pred))
    print('gaussian_naive_bayes_accuracy_score',accuracy_score(y_test,y_pred))
    print('gaussian_naive_bayes_f1_score',f1_score(y_test,y_pred, average='micro'))
    return y_pred

if __name__ == "__main__":
    print()

    data=pd.read_csv("/home/roopesh/Documents/Final_csv_prob/prob+label.csv", sep=',')
    data1=data.dropna(inplace=True)
    from sklearn import preprocessing
    from sklearn.preprocessing import LabelEncoder
    # Label_Encoding
    # le = LabelEncoder()
    # data['Iris_Color']= le.fit_transform(data['Iris_Color'])
    x= data[['Prob_R_pix','Prob_G_pix','Prob_B_pix','Prob_3rdComp']]
    y=data[['Iris_Color']]
    x1_train, x1_test, y1_train, y1_test = train_test_split(x,y,test_size=0.20, shuffle= True)
    # Normalizing the dataset
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    scaler.fit(x1_train)
    scaler.fit(x1_test)
    x1_train = scaler.transform(x1_train)
    x1_test = scaler.transform(x1_test)

    classification( x1_train,x1_test,y1_train,y1_test)







logistic_regression_classification_report               precision    recall  f1-score   support

       Black       0.48      1.00      0.65      1659
  Dark_Brown       0.00      0.00      0.00       888
        Grey       0.00      0.00      0.00       207
 Light_Brown       0.00      0.00      0.00       312
Medium_Brown       0.00      0.00      0.00       398

    accuracy                           0.48      3464
   macro avg       0.10      0.20      0.13      3464
weighted avg       0.23      0.48      0.31      3464

logistic_regression_confusion_matrix [[1659    0    0    0    0]
 [ 888    0    0    0    0]
 [ 207    0    0    0    0]
 [ 312    0    0    0    0]
 [ 398    0    0    0    0]]
logistic_regression_accuracy_score 0.4789260969976905
logistic_regression_f1_score 0.4789260969976905
random_forest_classification_report               precision    recall  f1-score   support

       Black       0.60      0.84      0.70      1659
  Dark_Brown       0.60      0.41      0.49